before_install:
- npm install -g gitbook-cli
script:
- gitbook init
- gitbook build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: "$GITHUB_API_KEY"
  keep-history: true
  verbose: true
  repo: sagolubev/sagolubev.github.io
  target-branch: master
  on:
    branch: master
  local_dir: _book
notifications:
  slack:
    secure: GfiqeaMoCzQA3sbkrVv2jElbpJEsgi3D2mFCTpWnK8QpVUDfv9GT4NBEOBUHSyoj3DMPL0QU+o5ueDuJoIE29Yw1dTzcPwhmd5oue1EhH29juL7qlw3pldMMuYE/fS5ElH/d39rGgqXcCmpfOLG9/1hnTdDBgWITDhmB34KX30NTnv+Woi0mBSS5r5hzhLekUa5ntZcahqDxKd1M/UmZ9Zf2HQ137Dug3mMO477Pz+uvqlAWbUU5kvmNHMB1Xi3YFsOF4//ShwOztkx/V8oAKfIub6rpQ0WCvJIsicQ8HxjfxN8HPlwZJ7nm4K8g4Sq6cfzqOTC8Ii/3N8ng8EzT6GRUbsPIb1eTlXDziLZsvSyRKQhRtn8SE3+Aa+9aiN+epUpmk4TCVZkwxSj1LjSgkcwvyhHFU5tMiZdmMN7F5yMm90cNcrSw090cpkfiWDBnolkicRWuEdaEHeeLc26aeyDGksCGVy0+Dqr4FGSkmsVxbbOYM0iDeKEMkeTbvy7ENPXgFoSeJiZo+egV2bFTCvejVVbufdxoyIZQuqMUgOO6ATykwp7kQXUbbnSg2P0Npi3RH/zryIrQLHiZT4f6388c0k+aeh6Xu2YO+4ZY59YVL2ZeslnBqrm9mlLytsPtKJ2UOXgxnYwTs5K2qVKfs8mt1vGPf5y/3vpNBGLa7Fw=
