[book]
title = "Tech Docs"
author = "Sergey Golubev"
description = "Technical Docs for interview."
language = "ru"
multilingual = false
src = "src"

[output.html]
google-analytics = "UA-42238316-4"
git-repository-url = "https://github.com/sagolubev/sagolubev.github.io"
git-repository-icon = "fa-github"
cname = "sigius.com"