name: Shared CI

on:
  pull_request:
  push:
    branches: [main, master]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  gitleaks:
    uses: sigiuscom/workflows/.github/workflows/gitleaks.yml@7c95f7784220fc87ffa82f8aa3a9e96145150ff7 # main
    secrets: inherit