name: Shared CI

on:
  pull_request:
  push:
    branches: [main, master]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  gitleaks:
    uses: sigiuscom/workflows/.github/workflows/gitleaks.yml@8ea3068a2c3df0b8b85387803faed536b266673b # main
    secrets: inherit