name: Shared CI

on:
  pull_request:
  push:
    branches: [main, master]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  gitleaks:
    uses: sigiuscom/workflows/.github/workflows/gitleaks.yml@be06407129c88c7b3cab2868d3daa47f4f91c055 # main
    secrets: inherit